version: '2'
services:
    site-app:
        image: site
        external_links:
            - site-mariadb:mariadb
            - site-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/site
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    site-mariadb:
        extends:
            file: mariadb.yml
            service: site-mariadb
    site-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: site-elasticsearch
