version: '2'
services:
    site-mariadb:
        container_name: site-mariadb
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/site/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=site
        ports:
            - 3306:3306
