version: '2'
services:
    politicos-app:
        image: politicos
        external_links:
            - politicos-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=politicos
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    politicos-mongodb:
        extends:
            file: mongodb.yml
            service: politicos-mongodb
