version: '2'
services:
    politicos-mongodb:
        container_name: politicos-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/politicos/mongodb/:/data/db/
